-- Migration: Fix Song Versions Schema (Rename audio -> soundcloud, add spotify)
-- Generated by Antigravity on 2026-01-17

-- 1. Rename audio_url to soundcloud_url if it exists as audio_url
DO $$
BEGIN
  IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='song_versions' AND column_name='audio_url') THEN
    ALTER TABLE public.song_versions RENAME COLUMN audio_url TO soundcloud_url;
  END IF;
END $$;

-- 2. Add spotify_url if missing
ALTER TABLE public.song_versions 
ADD COLUMN IF NOT EXISTS spotify_url text;

-- 3. Update comments (now safe as columns should exist)
COMMENT ON COLUMN public.song_versions.soundcloud_url IS 'Renamed from audio_url (v2.3)';
COMMENT ON COLUMN public.song_versions.spotify_url IS 'Added v2.3';
